# Generated by Django 4.1.4 on 2022-12-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cardText',
            field=models.TextField(blank=True),
        ),
    ]
