# Generated by Django 3.1.5 on 2022-12-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('desc', models.TextField()),
                ('title', models.TextField(default='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
