# Generated by Django 3.1.5 on 2022-12-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appie', '0002_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Article',
        ),
    ]
