# Generated by Django 4.1.4 on 2022-12-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appie', '0002_article_cardtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cardText',
            field=models.TextField(),
        ),
    ]
