# Generated by Django 4.1.4 on 2022-12-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appie', '0003_alter_article_cardtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.TextField()),
                ('video_link', models.TextField(help_text="width='383' height='210'")),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
