# Generated by Django 4.1.4 on 2022-12-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appie', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.TextField(),
        ),
    ]
