# Generated by Django 3.1.5 on 2022-12-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appie', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
