# Generated by Django 4.1.4 on 2022-12-28 12:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appie', '0005_alter_video_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.TextField(help_text='width="383" height="210"'),
        ),
    ]
